### ISSUE TITLE
Add ability to copy ssh/http urls for repository

### ISSUE THREAD

**Issue by atoftegaard-git** [rwilgaard/alfred-bitbucket-search#3]
It would be nice to have a way to copy clone urls for a repository, so you don't have to open the the repo in the browser before you can get the clone url.

**Comment by rwilgaard** [comment]
I have added this feature to release v1.1.0. The following key combinations can be used on a repository to copy the clone URLs:
• ⌘ ⇧ + ⏎ will copy SSH clone URL.
• ⌥ ⇧ + ⏎ will copy HTTP clone URL.
